name: Lint CMake

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master, develop]
    tags: ["*"]

defaults:
  run:
    shell: bash

jobs:
  gersemi:
    name: Gersemi Lint

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: read

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_ENV_HINTS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Linuxbrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Set up gersemi
        run: |
          brew install -q obsproject/tools/gersemi

      - name: Run Gersemi Lint
        run: |
          ./build-aux/run-gersemi --check
