name: Lint Src

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master, develop]
    tags: ["*"]

defaults:
  run:
    shell: bash

jobs:
  gersemi:
    name: Clang Format Lint

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: read

    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_ENV_HINTS: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Linuxbrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Set up Clang Format
        run: |
          brew install -q obsproject/tools/clang-format@19
          echo "/home/linuxbrew/.linuxbrew/opt/clang-format@19/bin" >> $GITHUB_PATH

      - name: Run Clang Format Lint
        run: |
          ./build-aux/run-clang-format --dry-run -Werror
